[package]
name = "rustrenderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
glfw = "0.47.0"
rgl = "0.2.0"
gl = "0.6.0"